image: python:2.7

pipelines:

  branches:
    develop:
      - step:
         script:
          - echo "deploy staging"
          - pip install "fabric==1.13.2"
          - fab staging deploy --abort-on-prompts copy_media_files -i /opt/atlassian/pipelines/agent/data/id_rsa
  custom:
    deploy:
      - step:
         script: # Modify the commands below to build your repository.
          - echo "deploy"
          - pip install "fabric==1.13.2"
          - fab production deploy --abort-on-prompts -i /opt/atlassian/pipelines/agent/data/id_rsa
    deploy_staging:
      - step:
         script: # Modify the commands below to build your repository.
          - echo "deploy staging"
          - pip install "fabric==1.13.2"
          - fab staging deploy copy_media_files --abort-on-prompts -i /opt/atlassian/pipelines/agent/data/id_rsa