version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/PROJECT_NAME
    tty: true
    command: python -u manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  gulp:
    build: ./gulp
    volumes:
      - .:/PROJECT_NAME
      - /PROJECT_NAME/gulp/node_modules
    command: gulp watch
  db:
   image: postgres:latest
   environment:
     - POSTGRES_USER=PROJECT_NAME
     - POSTGRES_PASSWORD=12345
     - POSTGRES_DB=PROJECT_NAME
   volumes:
     - ./docker/postgresql:/var/lib/postgresql
   expose:
    - "5432"
