version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/PROJECT_NAME
    tty: true
    restart: always
    command: sh -c "./docker/wait-for-it.sh -c 'nc -z db 5432' -t 30 && python manage.py runserver 0.0.0.0:8000"
  gulp:
    build: ./gulp
    volumes:
      - .:/PROJECT_NAME
      - /PROJECT_NAME/gulp/node_modules
    ports:
      - "3000:3000"
      - "3001:3001"
    restart: always
    command: gulp browsersync
  db:
   image: postgres:alpine
   environment:
     - POSTGRES_USER=PROJECT_NAME
     - POSTGRES_PASSWORD=12345
     - POSTGRES_DB=PROJECT_NAME
   volumes:
     - ./docker/postgresql:/var/lib/postgresql
   expose:
    - "5432"
  redis:
    image: redis:alpine

