version: '2'
services:
  web-startup:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/PROJECT_NAME
    command: ./config/web/startup.sh
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/PROJECT_NAME
    command: ./config/web/run.sh
  gulp:
    build: ./config/gulp
    volumes:
      - .:/PROJECT_NAME
    command: ./PROJECT_NAME/config/gulp/gulp.sh