FROM python:3.6-slim
COPY . /PROJECT_NAME
WORKDIR /PROJECT_NAME
COPY pip.conf /root/.pip/pip.conf
RUN apt-get update -y && apt-get update -y && apt-get install libjpeg-dev build-essential libproj-dev netcat -y &&\
    groupadd uwsgi &&\
    useradd -g uwsgi uwsgi &&\
    mkdir /tmp/uwsgi && chown -R uwsgi:101 /tmp/uwsgi &&\
    chown -R uwsgi:101 /PROJECT_NAME &&\
    pip install pip==9.0.3 &&\
    pip install -Ur requirements.txt &&\
    pip install https://projects.unbit.it/downloads/uwsgi-lts.tar.gz
CMD sh -c "uwsgi PROJECT_NAME-prod.ini"